### ISSUE TITLE
Error: Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by spyderman4g63** [IBM/watson-discovery-ui#112]
I'm getting this error when trying to run npm start. I've updated npm and node to the latest versions. Any idea of what could be causing this?

```
/Users/jward/Desktop/watson-discovery-ui/node_modules/express-browserify/index.js:104
				throw err;
				^

Error: Couldn't find preset "es2015" relative to directory "/Users/jward/Desktop/watson-discovery-ui" while parsing file: /Users/jward/Desktop/watson-discovery-ui/public/js/bundle.js
    at /Users/jward/Desktop/watson-discovery-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/jward/Desktop/watson-discovery-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/jward/Desktop/watson-discovery-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/jward/Desktop/watson-discovery-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/jward/Desktop/watson-discovery-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/jward/Desktop/watson-discovery-ui/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/jward/Desktop/watson-discovery-ui/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/jward/Desktop/watson-discovery-ui/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Babelify._flush (/Users/jward/Desktop/watson-discovery-ui/node_modules/babelify/index.js:26:24)
    at Babelify.prefinish (_stream_transform.js:136:10)
    at Babelify.emit (events.js:127:13)
    at prefinish (_stream_writable.js:621:14)
    at finishMaybe (_stream_writable.js:629:5)
    at endWritable (_stream_writable.js:640:3)
    at Babelify.Writable.end (_stream_writable.js:582:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! watson-discovery-ui@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the watson-discovery-ui@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jward/.npm/_logs/2018-03-05T19_33_11_802Z-debug.log
```

**Comment by markstur** [comment]
@spyderman4g63 I think we need to add a dependency, but can you confirm?  Does running the following in your cloned dir fix the problem?

npm install --save babel-preset-es2015

**Comment by spyderman4g63** [comment]
npm is failing when trying to install that.

```
npm ERR! path /Users/jward/Desktop/watson-discovery-ui/node_modules/npm/node_modules/dezalgo
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/jward/Desktop/watson-discovery-ui/node_modules/npm/node_modules/dezalgo' -> '/Users/jward/Desktop/watson-discovery-ui/node_modules/npm/node_modules/.dezalgo.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jward/.npm/_logs/2018-03-05T19_44_59_403Z-debug.log
```

**Comment by rhagarty** [comment]
sometime re-setting clears up the dezalgo issue:

rm -rf node_modules
npm install

**Comment by spyderman4g63** [comment]
OK, I did that and now I can run the server without errors. Thanks.
